# Generated by Django 2.2.1 on 2019-05-14 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Jan', max_length=120)),
                ('last_name', models.CharField(max_length=45)),
                ('phone', models.BigIntegerField(default=1000000000000, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(15)])),
                ('is_working', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField(default='')),
                ('last_update', models.DateField(default='')),
                ('new', models.TextField(default='ab')),
            ],
        ),
    ]
