# Generated by Django 2.2.1 on 2019-05-14 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190514_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.BigIntegerField(default=10, validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
