# Generated by Django 2.2.1 on 2019-05-14 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190514_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='phone',
            field=models.BigIntegerField(default=1000000000000, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(15)]),
        ),
    ]
