# Generated by Django 2.2.1 on 2019-05-14 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190514_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposition',
            name='new',
        ),
        migrations.RemoveField(
            model_name='jobposition',
            name='phone',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.BigIntegerField(default=1000000000000, validators=[django.core.validators.MinValueValidator(100000000), django.core.validators.MaxValueValidator(999999999999999)]),
        ),
    ]
