# Generated by Django 2.2.1 on 2019-05-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190514_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
