# Generated by Django 2.2.1 on 2019-05-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_employee_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='comment',
            field=models.TextField(),
        ),
    ]
