# Generated by Django 2.2.1 on 2019-05-14 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_employee_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 14, 15, 35, 1, 183942)),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2019, 5, 14, 15, 35, 1, 183967)),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
