# Generated by Django 2.2.1 on 2019-05-14 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190514_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 14, 15, 44, 37, 300812)),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2019, 5, 14, 15, 44, 37, 300839)),
        ),
    ]
