# Generated by Django 2.2.1 on 2019-05-14 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20190514_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2019, 5, 14, 16, 17, 8, 881278)),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 14, 16, 17, 8, 881699)),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2019, 5, 14, 16, 17, 8, 881720)),
        ),
    ]
